package com.mealflex.complaint.service;
import com.mealflex.common.exception.*; import com.mealflex.complaint.dto.ComplaintAttachmentResponse; import com.mealflex.complaint.entity.*; import com.mealflex.complaint.repository.*;
import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.core.io.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
import java.io.*; import java.nio.file.*; import java.util.*;
@Service @RequiredArgsConstructor public class ComplaintAttachmentService {
 private static final Map<String,String> TYPES=Map.of("application/pdf",".pdf","image/jpeg",".jpg","image/png",".png"); private static final long MAX=10L*1024*1024;
 private final ComplaintRepository complaints; private final ComplaintAttachmentRepository attachments; @Value("${app.upload-dir:uploads}") private String uploadDir;
 @Transactional public ComplaintAttachmentResponse upload(Long customerId,Long complaintId,MultipartFile file){Complaint c=complaints.findById(complaintId).orElseThrow(()->new ResourceNotFoundException("Şikâyet",complaintId));if(!c.getCustomer().getId().equals(customerId))throw new BusinessException("UNAUTHORIZED_ACCESS","Bu şikâyet size ait değil.");validate(file);String stored="complaint-"+UUID.randomUUID()+TYPES.get(file.getContentType());Path dir=directory(complaintId),target=dir.resolve(stored).normalize();if(!target.startsWith(dir))throw new BusinessException("INVALID_FILE_PATH","Geçersiz dosya yolu.");try{Files.createDirectories(dir);try(InputStream in=file.getInputStream()){Files.copy(in,target,StandardCopyOption.REPLACE_EXISTING);}}catch(IOException e){throw new BusinessException("ATTACHMENT_UPLOAD_FAILED","Ek dosya kaydedilemedi.");}ComplaintAttachment a=attachments.save(ComplaintAttachment.builder().complaint(c).fileName(sanitize(file.getOriginalFilename())).storageName(stored).contentType(file.getContentType()).fileSize(file.getSize()).build());return response(a,false);}
 @Transactional(readOnly=true) public List<ComplaintAttachmentResponse> listForAdmin(Long complaintId){complaints.findById(complaintId).orElseThrow(()->new ResourceNotFoundException("Şikâyet",complaintId));return attachments.findByComplaintIdOrderByCreatedAtAsc(complaintId).stream().map(a->response(a,true)).toList();}
 @Transactional(readOnly=true) public Resource loadForAdmin(Long complaintId,Long attachmentId){ComplaintAttachment a=attachments.findById(attachmentId).filter(x->x.getComplaint().getId().equals(complaintId)).orElseThrow(()->new ResourceNotFoundException("Şikâyet eki",attachmentId));Path file=directory(complaintId).resolve(a.getStorageName()).normalize();if(!file.startsWith(directory(complaintId)))throw new BusinessException("INVALID_FILE_PATH","Geçersiz dosya yolu.");try{Resource r=new UrlResource(file.toUri());if(!r.exists()||!r.isReadable())throw new ResourceNotFoundException("Şikâyet eki",attachmentId);return r;}catch(IOException e){throw new ResourceNotFoundException("Şikâyet eki",attachmentId);}}
 private Path directory(Long id){return Path.of(uploadDir).toAbsolutePath().normalize().resolve("complaints").resolve(id.toString());} private void validate(MultipartFile f){if(f==null||f.isEmpty())throw new BusinessException("ATTACHMENT_REQUIRED","Ek dosya zorunludur.");if(!TYPES.containsKey(f.getContentType()))throw new BusinessException("INVALID_ATTACHMENT_TYPE","Yalnız PDF, JPG veya PNG yüklenebilir.");if(f.getSize()>MAX)throw new BusinessException("ATTACHMENT_TOO_LARGE","Ek dosya 10 MB'den büyük olamaz.");} private String sanitize(String n){return n==null?"ek":n.replaceAll("[^a-zA-Z0-9._-]","_");} private ComplaintAttachmentResponse response(ComplaintAttachment a,boolean admin){return new ComplaintAttachmentResponse(a.getId(),a.getFileName(),a.getContentType(),a.getFileSize(),admin?"/api/v1/admin/complaints/"+a.getComplaint().getId()+"/attachments/"+a.getId()+"/file":"");}
}
