package com.mealflex.seller.service;
import com.mealflex.common.exception.*;
import com.mealflex.audit.entity.AuditLog;
import com.mealflex.audit.repository.AuditLogRepository;
import com.mealflex.seller.dto.StoreStaffResponse;
import com.mealflex.seller.entity.StoreStaff;
import com.mealflex.seller.repository.StoreStaffRepository;
import com.mealflex.store.service.SellerStoreAccessService;
import com.mealflex.user.entity.User;
import com.mealflex.user.repository.UserRepository;
import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*;

@Service @RequiredArgsConstructor public class StoreStaffService {
 public static final Set<String> ROLES=Set.of("OWNER","STORE_MANAGER","OPERATIONS","KITCHEN","COURIER","FINANCE");
 private final StoreStaffRepository repository; private final SellerStoreAccessService storeAccess; private final UserRepository users; private final AuditLogRepository auditLogs;
 public static Set<String> permissions(String role){ return switch(role){case "OWNER"->Set.of("*"); case "STORE_MANAGER"->Set.of("STORE_MANAGE","MENU_MANAGE","STAFF_MANAGE","SUBSCRIPTION_MANAGE","DELIVERY_MANAGE","DOCUMENT_MANAGE");case "OPERATIONS"->Set.of("SUBSCRIPTION_MANAGE","DELIVERY_MANAGE","CUSTOMER_CONTACT");case "KITCHEN"->Set.of("PRODUCTION_VIEW","MENU_VIEW");case "COURIER"->Set.of("DELIVERY_VIEW","DELIVERY_UPDATE","CUSTOMER_CONTACT_MASKED");case "FINANCE"->Set.of("FINANCE_VIEW","PAYOUT_VIEW");default->Set.of();}; }
 @Transactional(readOnly=true) public List<StoreStaffResponse> list(Long owner,Long store){storeAccess.requireOwnedStore(owner,store);return repository.findByStoreIdAndDeletedAtIsNullOrderByCreatedAtDesc(store).stream().map(this::response).toList();}
 @Transactional public StoreStaffResponse invite(Long owner,Long store,String email,String role){storeAccess.requireOwnedStore(owner,store); String normalized=email==null?"":email.trim().toLowerCase(); if(!ROLES.contains(role))throw new BusinessException("INVALID_STAFF_ROLE","Geçersiz personel rolü."); if(normalized.isBlank())throw new BusinessException("STAFF_EMAIL_REQUIRED","Personel e-postası zorunludur."); User inviter=users.findById(owner).orElseThrow(()->new ResourceNotFoundException("Kullanıcı",owner)); StoreStaff staff=repository.findByStoreIdAndDeletedAtIsNullOrderByCreatedAtDesc(store).stream().filter(s->s.getEmail().equals(normalized)).findFirst().orElse(StoreStaff.builder().store(storeAccess.requireOwnedStore(owner,store)).email(normalized).invitedBy(inviter).build()); staff.setStaffRole(role);staff.setStatus("INVITED");staff.setInvitationTokenHash(com.mealflex.user.service.AccountSecurityService.hash(UUID.randomUUID().toString()));staff.setInvitationExpiresAt(Instant.now().plus(Duration.ofDays(7)));staff.setDeactivatedAt(null);staff=repository.save(staff);audit(owner,"STAFF_INVITED",staff,"role="+role);return response(staff);}
 @Transactional public StoreStaffResponse accept(Long userId,String token){StoreStaff staff=repository.findByInvitationTokenHashAndStatus(com.mealflex.user.service.AccountSecurityService.hash(token==null?"":token),"INVITED").orElseThrow(()->new BusinessException("INVALID_INVITATION","Davet geçersiz."));if(staff.getInvitationExpiresAt().isBefore(Instant.now()))throw new BusinessException("EXPIRED_INVITATION","Davetin süresi dolmuş.");User user=users.findById(userId).orElseThrow(()->new ResourceNotFoundException("Kullanıcı",userId));if(!staff.getEmail().equalsIgnoreCase(user.getEmail()))throw new BusinessException("INVITATION_EMAIL_MISMATCH","Davet başka bir e-posta adresine ait.");staff.setUser(user);staff.setStatus("ACTIVE");staff.setAcceptedAt(Instant.now());staff.setInvitationTokenHash(null);return response(repository.save(staff));}
 @Transactional public void cancelOrDeactivate(Long owner,Long store,Long staffId){storeAccess.requireOwnedStore(owner,store);StoreStaff staff=repository.findByIdAndStoreIdAndDeletedAtIsNull(staffId,store).orElseThrow(()->new ResourceNotFoundException("Personel",staffId));staff.setStatus("DEACTIVATED");staff.setDeactivatedAt(Instant.now());repository.save(staff);audit(owner,"STAFF_DEACTIVATED",staff,null);}
 @Transactional(readOnly=true) public void require(Long userId,Long store,String permission){if(storeAccess.isOwner(userId,store))return;StoreStaff staff=repository.findByStoreIdAndUserIdAndStatus(store,userId,"ACTIVE").orElseThrow(()->new BusinessException("STAFF_PERMISSION_DENIED","Bu mağaza için yetkiniz yok."));Set<String> allowed=permissions(staff.getStaffRole());if(!allowed.contains("*")&&!allowed.contains(permission))throw new BusinessException("STAFF_PERMISSION_DENIED","Bu işlem için yetkiniz yok.");}
 private StoreStaffResponse response(StoreStaff s){String name=s.getUser()==null?null:s.getUser().getFirstName()+" "+s.getUser().getLastName();return StoreStaffResponse.builder().id(s.getId()).email(s.getEmail()).fullName(name).role(s.getStaffRole()).status(s.getStatus()).permissions(permissions(s.getStaffRole())).invitationExpiresAt(s.getInvitationExpiresAt()).acceptedAt(s.getAcceptedAt()).build();}
 private void audit(Long actor,String action,StoreStaff staff,String detail){auditLogs.save(AuditLog.builder().actorId(actor).action(action).entityType("STORE_STAFF").entityId(staff.getId()).newValue(detail).timestamp(Instant.now()).build());}
}
