ALTER TABLE invoices ADD COLUMN IF NOT EXISTS provider VARCHAR(40) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS provider_document_id VARCHAR(150);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS delivery_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_ISSUANCE';
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS emailed_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS integration_api_keys (
  id BIGSERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, key_prefix VARCHAR(16) NOT NULL,
  key_hash VARCHAR(255) NOT NULL, scopes VARCHAR(500) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
  last_used_at TIMESTAMP WITH TIME ZONE, expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS webhook_subscriptions (
  id BIGSERIAL PRIMARY KEY, target_url VARCHAR(1000) NOT NULL, secret_hash VARCHAR(255) NOT NULL,
  event_types VARCHAR(1000) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, failure_count INTEGER NOT NULL DEFAULT 0,
  last_attempt_at TIMESTAMP WITH TIME ZONE, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS automation_tasks (
  id BIGSERIAL PRIMARY KEY, task_type VARCHAR(80) NOT NULL, payload TEXT, status VARCHAR(30) NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0, run_after TIMESTAMP WITH TIME ZONE NOT NULL, last_error VARCHAR(1000),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_automation_tasks_due ON automation_tasks(status, run_after);

CREATE TABLE IF NOT EXISTS feature_flags (
  id BIGSERIAL PRIMARY KEY, flag_key VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(500), enabled BOOLEAN NOT NULL DEFAULT FALSE,
  rollout_percent INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS product_analytics_events (
  id BIGSERIAL PRIMARY KEY, event_name VARCHAR(100) NOT NULL, actor_id BIGINT, properties_json TEXT,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_product_analytics_events_name_time ON product_analytics_events(event_name, occurred_at);
