package com.mealflex.campaign.service;
import com.mealflex.campaign.dto.*; import com.mealflex.campaign.entity.*; import com.mealflex.campaign.repository.*; import com.mealflex.common.exception.*; import com.mealflex.menu.entity.Menu; import com.mealflex.menu.repository.MenuRepository; import com.mealflex.store.entity.Store; import com.mealflex.store.service.SellerStoreAccessService; import com.mealflex.subscription.entity.Subscription; import com.mealflex.subscription.repository.SubscriptionRepository; import com.mealflex.user.entity.User; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class CampaignService {
 private final CampaignRepository campaigns; private final CampaignRedemptionRepository redemptions; private final MenuRepository menus; private final SellerStoreAccessService storeAccess; private final SubscriptionRepository subscriptions;
 @Transactional public CampaignResponse create(Long seller,Long storeId,CampaignRequest request){Store store=storeAccess.requireOwnedStore(seller,storeId);validateRequest(request);Menu menu=request.getMenuId()==null?null:menus.findById(request.getMenuId()).filter(m->m.getStore().getId().equals(storeId)).orElseThrow(()->new BusinessException("CAMPAIGN_MENU_INVALID","Kampanya menüsü bu mağazaya ait değil."));Campaign campaign=Campaign.builder().store(store).menu(menu).name(request.getName().trim()).code(normalize(request.getCode())).campaignType(request.getCampaignType().toUpperCase()).discountValue(nz(request.getDiscountValue())).minAmount(request.getMinAmount()).maxUsesPerCustomer(request.getMaxUsesPerCustomer()==null?1:request.getMaxUsesPerCustomer()).firstSubscriptionOnly(request.isFirstSubscriptionOnly()).corporateCode(normalize(request.getCorporateCode())).corporatePricePerPerson(request.getCorporatePricePerPerson()).referralReward(request.getReferralReward()).startDate(request.getStartDate()).endDate(request.getEndDate()).sellerShareRate(nz(request.getSellerShareRate())).platformShareRate(request.getPlatformShareRate()==null?BigDecimal.ONE:request.getPlatformShareRate()).build();return response(campaigns.save(campaign));}
 @Transactional(readOnly=true) public List<CampaignResponse> list(Long seller,Long store){storeAccess.requireOwnedStore(seller,store);return campaigns.findByStoreIdAndDeletedAtIsNullOrderByCreatedAtDesc(store).stream().map(this::response).toList();}
 @Transactional public void setActive(Long seller,Long store,Long id,boolean active){storeAccess.requireOwnedStore(seller,store);Campaign c=campaigns.findById(id).filter(x->x.getStore()!=null&&x.getStore().getId().equals(store)).orElseThrow(()->new ResourceNotFoundException("Kampanya",id));c.setActive(active);campaigns.save(c);}
 @Transactional(readOnly=true) public Quote quote(Long customer,Long storeId,Long menuId,BigDecimal gross,String code,int serviceDays,int persons){Campaign campaign=findValid(code,storeId,menuId,gross,customer);if(campaign!=null&&campaign.getTargetCustomer()!=null&&!campaign.getTargetCustomer().getId().equals(customer))throw new BusinessException("COUPON_CUSTOMER_INVALID","Bu telafi kuponu başka bir müşteriye aittir.");BigDecimal discount=discount(campaign,gross,serviceDays,persons);return new Quote(campaign,discount,gross.subtract(discount).max(BigDecimal.ZERO));}
 @Transactional public void redeem(Campaign campaign,User customer,Subscription subscription,BigDecimal discount){if(campaign==null||discount.signum()<=0)return;redemptions.save(CampaignRedemption.builder().campaign(campaign).customer(customer).subscription(subscription).discountAmount(discount).build());}
 private Campaign findValid(String code,Long store,Long menu,BigDecimal gross,Long user){if(code==null||code.isBlank())return null;Campaign c=campaigns.findByCodeIgnoreCaseAndActiveTrueAndDeletedAtIsNull(code.trim()).orElseThrow(()->new BusinessException("COUPON_INVALID","Kupon bulunamadı veya aktif değil."));LocalDate today=com.mealflex.subscription.service.SubscriptionDatePolicy.today();if(c.getStartDate().isAfter(today)||c.getEndDate().isBefore(today))throw new BusinessException("COUPON_EXPIRED","Kuponun kullanım tarihi uygun değil.");if(c.getStore()!=null&&!c.getStore().getId().equals(store))throw new BusinessException("COUPON_STORE_INVALID","Kupon bu mağazada geçerli değil.");if(c.getMenu()!=null&&!c.getMenu().getId().equals(menu))throw new BusinessException("COUPON_MENU_INVALID","Kupon bu menüde geçerli değil.");if(c.getMinAmount()!=null&&gross.compareTo(c.getMinAmount())<0)throw new BusinessException("COUPON_MIN_AMOUNT","Kupon için minimum tutara ulaşılmadı.");if(redemptions.countByCampaignIdAndCustomerId(c.getId(),user)>=c.getMaxUsesPerCustomer())throw new BusinessException("COUPON_USAGE_LIMIT","Bu kuponun kullanım sınırına ulaştınız.");if(c.isFirstSubscriptionOnly()&&!subscriptions.findByCustomerId(user,org.springframework.data.domain.Pageable.ofSize(1)).isEmpty())throw new BusinessException("COUPON_FIRST_ONLY","Bu kupon yalnızca ilk abonelikte kullanılabilir.");return c;}
 private BigDecimal discount(Campaign c,BigDecimal gross,int serviceDays,int people){if(c==null)return BigDecimal.ZERO;return switch(c.getCampaignType()){case "PERCENT"->gross.multiply(c.getDiscountValue()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP).min(gross);case "FIXED","REFERRAL"->c.getDiscountValue().min(gross);case "FREE_DAYS"->gross.multiply(c.getDiscountValue()).divide(BigDecimal.valueOf(Math.max(1,serviceDays)),2,RoundingMode.HALF_UP).min(gross);case "CORPORATE"->c.getCorporatePricePerPerson()==null?BigDecimal.ZERO:gross.subtract(c.getCorporatePricePerPerson().multiply(BigDecimal.valueOf(people)).multiply(BigDecimal.valueOf(serviceDays))).max(BigDecimal.ZERO);default->throw new BusinessException("CAMPAIGN_TYPE_INVALID","Kampanya tipi geçersiz.");};}
 private void validateRequest(CampaignRequest r){if(r.getName()==null||r.getName().isBlank()||r.getCampaignType()==null||r.getStartDate()==null||r.getEndDate()==null||r.getEndDate().isBefore(r.getStartDate()))throw new BusinessException("CAMPAIGN_INVALID","Kampanya adı, tipi ve tarih aralığı zorunludur.");if(!Set.of("PERCENT","FIXED","FREE_DAYS","CORPORATE","REFERRAL").contains(r.getCampaignType().toUpperCase()))throw new BusinessException("CAMPAIGN_TYPE_INVALID","Kampanya tipi geçersiz.");}
 private String normalize(String value){return value==null||value.isBlank()?null:value.trim().toUpperCase(Locale.ROOT);} private BigDecimal nz(BigDecimal value){return value==null?BigDecimal.ZERO:value;}
 private CampaignResponse response(Campaign c){return CampaignResponse.builder().id(c.getId()).name(c.getName()).code(c.getCode()).campaignType(c.getCampaignType()).discountValue(c.getDiscountValue()).minAmount(c.getMinAmount()).maxUsesPerCustomer(c.getMaxUsesPerCustomer()).firstSubscriptionOnly(c.isFirstSubscriptionOnly()).startDate(c.getStartDate()).endDate(c.getEndDate()).active(c.isActive()).sellerShareRate(c.getSellerShareRate()).platformShareRate(c.getPlatformShareRate()).build();}
 public record Quote(Campaign campaign,BigDecimal discount,BigDecimal total){}
}
