CREATE TABLE couriers (
 id BIGSERIAL PRIMARY KEY, store_id BIGINT NOT NULL REFERENCES stores(id), full_name VARCHAR(150) NOT NULL,
 phone VARCHAR(40), active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_at TIMESTAMPTZ
);
ALTER TABLE subscription_deliveries ADD COLUMN IF NOT EXISTS courier_id BIGINT REFERENCES couriers(id);
ALTER TABLE subscription_deliveries ADD COLUMN IF NOT EXISTS route_sequence INTEGER;
ALTER TABLE subscription_deliveries ADD COLUMN IF NOT EXISTS delivery_type VARCHAR(30) NOT NULL DEFAULT 'STORE_COURIER';
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS seller_response TEXT;
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS escalated_at TIMESTAMPTZ;
ALTER TABLE complaints ADD COLUMN IF NOT EXISTS attachment_urls TEXT;
