ALTER TABLE menu_versions ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE menu_schedule_versions ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE couriers ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
