CREATE TABLE public.support_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id),
    account_role character varying(30) NOT NULL,
    contact_name character varying(120) NOT NULL,
    contact_email character varying(255) NOT NULL,
    contact_phone character varying(25),
    category character varying(30) NOT NULL,
    subject character varying(150) NOT NULL,
    message text NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'NEW',
    admin_response text,
    responded_at timestamp with time zone,
    responded_by_user_id bigint REFERENCES public.users(id),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    version bigint,
    deleted_at timestamp with time zone
);

CREATE INDEX idx_support_requests_status_created
    ON public.support_requests (status, created_at DESC);
