CREATE TABLE public.support_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id),
    account_role character varying(30) NOT NULL,
    contact_name character varying(120) NOT NULL,
    contact_email character varying(255) NOT NULL,
    contact_phone character varying(25),
    category character varying(30) NOT NULL,
    subject character varying(150) NOT NULL,
    message text NOT NULL,
    email_status character varying(20) NOT NULL DEFAULT 'PENDING',
    email_attempts integer NOT NULL DEFAULT 0,
    next_email_attempt_at timestamp with time zone,
    email_sent_at timestamp with time zone,
    last_email_error character varying(500),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    version bigint,
    deleted_at timestamp with time zone
);

CREATE INDEX idx_support_requests_email_delivery
    ON public.support_requests (email_status, next_email_attempt_at, created_at);

