package com.mealflex.notification.service;
import com.mealflex.notification.entity.*; import com.mealflex.notification.repository.*; import com.mealflex.user.entity.User; import com.mealflex.user.repository.NotificationPreferenceRepository; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
/** Central outbox: in-app delivery is synchronous; external channels remain retryable and provider-neutral. */
@Service @RequiredArgsConstructor public class NotificationEventService {
 private final NotificationEventRepository events; private final NotificationRepository notifications; private final NotificationPreferenceRepository preferences;
 @Transactional public void publish(User user,String type,String title,String body,String referenceType,Long referenceId){var pref=preferences.findByUserId(user.getId()).orElse(null);String channels="IN_APP"+(pref==null||pref.isPushEnabled()?",PUSH":"")+(pref==null||pref.isEmailEnabled()?",EMAIL":"")+(pref!=null&&pref.isSmsEnabled()?",SMS":""); NotificationEvent event=events.save(NotificationEvent.builder().user(user).eventType(type).channels(channels).title(title).body(body).referenceType(referenceType).referenceId(referenceId).nextAttemptAt(Instant.now()).build()); notifications.save(Notification.builder().user(user).title(title).message(body).referenceType(referenceType).referenceId(referenceId).build()); event.setStatus("DELIVERED_IN_APP");events.save(event); }
 @Transactional public void retryPending(){events.findTop100ByStatusAndNextAttemptAtBeforeOrderByCreatedAtAsc("RETRY",Instant.now()).forEach(event->{event.setAttempts(event.getAttempts()+1);event.setNextAttemptAt(Instant.now().plus(Duration.ofMinutes(Math.min(60,event.getAttempts()*5L))));events.save(event);});}
 public static String deepLink(String type,Long id){if(id==null)return "/notifications";return switch(type==null?"":type){case "SUBSCRIPTION","SUBSCRIPTION_DELIVERY"->"/subscriptions/"+id;case "PAYMENT","REFUND"->"/account/payments/"+id;case "STORE"->"/stores/"+id;default->"/notifications";};}
}
